language: scala
scala:
 - 2.11.6
jdk:
 - oraclejdk8
env:
 global:
  - TRAVIS_JDK_VERSION=oraclejdk8Thx!
  - CODACY_PROJECT_TOKEN=36dd798d665d40db9f14eef201af7986
  - secure: Hjba3GX9/l9cfTdB6kq3rwNz28/VCOjDKeGR29k6KCazSxx+owIXVBD267QDCJDeyuHKNf0Nx3usFHIeUYsRtOk4n421T2Yu52ovtuUGIsgD6DeW1uTvv7bdpFKlyfEZIDtRNNkT8GFYvhJe7tBgmpWWXZi1A2iY5EpIG9YaSWizHIp6OK8XayaZkQBsmPDjHO3Do0kAuDzUu1E/Tm+Cq0EvEZi4NfVqHS4gcP61qrt8978q75PsxZ3Ai8a8aVLuQnGjF7O42JscLDb5k8K6faLn+Eb6l4YCMz/cn4LD7l/4HcaCxuVkYp9d2NaZKXDWE3t3gHtORRKZ4DUzHSVrK8KtRSst0OuKABFh2iF/JsxjBYUekypStp5TaKZEUU/nBKiFjH903YJUSKfzJj2OGWk4SR0yu3Gy5wjQKsc8t0+AUw+W729EoaC2aLpg65wgIjEB9qZVGiyM7lX6Phc6WWxTjN4BMBny4m7xx7GMbAMi9cUKuokADj60AceopfUlL2SWLGa8ht05dNNTcbVff3ndVwtgbBNy+LVTzOdKaX/b4oXbuNAWtAMGpPKx8/iSsHUVqtf05WbuWMyBsyNw4ODm7AGyKVwX13066Yagd4HBNTWWalwzddhZBQLKzfbakOg4yeNfSX5XvLZTVhLZdEQkAgVQfbJSAmhVTlwHTo8=
  - secure: cA9hORM/lgmEnoueBGPwcb6zfi8/nuJJ2eDhaAxfmHaeysfJL6s2UwveK5cG46oAN8jueh3afA8b2XbE5i+fspa6g69t7S9l8LLmFYwCuZ8H+J79X4JJHOZXDhuknLAKT6JCSfITlDAXlfqcw/jNSBcvy6OoOCwrgw/7QNb8ydbHI/2fC/0nkJRf2lohKZI1+h/MTFNww+wEBpMvzLmUKFTfS9PiQTouncvSQAB2N3+A+K1s91B39mXwluKpWnWMWcBhf+KQvpQSo1Lg0n7rh7wetvngrie0+sWbWN75XpCF7Xnqcsi4tjvA01X8RnuWpsItHvF6Zww3PFEaO202pqrAZcxmTbf3k59THu0pbVCBxz9Z/H/0O37YldPK5EKrF9Tk363df9SiSTwGBblfPs5RdysSwrthiCQlVSiJUhWtD0+p/rSaKYJSpDyjv0CyG/f3zWUyYiKjjfgdIKDWTwHbAapm5uNMy5IgRMSE0fzRfFEBPHpCu4y00bXeIMTB6fnnks2ddj6JMBHkY0KKeDiXH4Jyn42lRLPouq2mPAfp2xsTUfVNmvcnOQbc2tRmP9MGO7FM41f1vZFndiV/Ek4uFojdfPJIpHgM1aSWsraJLCmZmDN7r6jEuUxesKJTmWt/6zqKYK5ZmlP835U7bTiE3JDL1vHfdZ/WO1GUKig=
script:
  - sbt clean coverage test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
after_success:
 - >
  test "${TRAVIS_PULL_REQUEST}" = 'false' &&
  test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' &&
  sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6120fddea5fd58b6bc51
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
