language: scala
scala:
 - 2.11.8
 - 2.12.8
jdk:
 - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

env:
 global:
  - TRAVIS_JDK_VERSION=oraclejdk8
  - secure: Hjba3GX9/l9cfTdB6kq3rwNz28/VCOjDKeGR29k6KCazSxx+owIXVBD267QDCJDeyuHKNf0Nx3usFHIeUYsRtOk4n421T2Yu52ovtuUGIsgD6DeW1uTvv7bdpFKlyfEZIDtRNNkT8GFYvhJe7tBgmpWWXZi1A2iY5EpIG9YaSWizHIp6OK8XayaZkQBsmPDjHO3Do0kAuDzUu1E/Tm+Cq0EvEZi4NfVqHS4gcP61qrt8978q75PsxZ3Ai8a8aVLuQnGjF7O42JscLDb5k8K6faLn+Eb6l4YCMz/cn4LD7l/4HcaCxuVkYp9d2NaZKXDWE3t3gHtORRKZ4DUzHSVrK8KtRSst0OuKABFh2iF/JsxjBYUekypStp5TaKZEUU/nBKiFjH903YJUSKfzJj2OGWk4SR0yu3Gy5wjQKsc8t0+AUw+W729EoaC2aLpg65wgIjEB9qZVGiyM7lX6Phc6WWxTjN4BMBny4m7xx7GMbAMi9cUKuokADj60AceopfUlL2SWLGa8ht05dNNTcbVff3ndVwtgbBNy+LVTzOdKaX/b4oXbuNAWtAMGpPKx8/iSsHUVqtf05WbuWMyBsyNw4ODm7AGyKVwX13066Yagd4HBNTWWalwzddhZBQLKzfbakOg4yeNfSX5XvLZTVhLZdEQkAgVQfbJSAmhVTlwHTo8=
  - secure: cA9hORM/lgmEnoueBGPwcb6zfi8/nuJJ2eDhaAxfmHaeysfJL6s2UwveK5cG46oAN8jueh3afA8b2XbE5i+fspa6g69t7S9l8LLmFYwCuZ8H+J79X4JJHOZXDhuknLAKT6JCSfITlDAXlfqcw/jNSBcvy6OoOCwrgw/7QNb8ydbHI/2fC/0nkJRf2lohKZI1+h/MTFNww+wEBpMvzLmUKFTfS9PiQTouncvSQAB2N3+A+K1s91B39mXwluKpWnWMWcBhf+KQvpQSo1Lg0n7rh7wetvngrie0+sWbWN75XpCF7Xnqcsi4tjvA01X8RnuWpsItHvF6Zww3PFEaO202pqrAZcxmTbf3k59THu0pbVCBxz9Z/H/0O37YldPK5EKrF9Tk363df9SiSTwGBblfPs5RdysSwrthiCQlVSiJUhWtD0+p/rSaKYJSpDyjv0CyG/f3zWUyYiKjjfgdIKDWTwHbAapm5uNMy5IgRMSE0fzRfFEBPHpCu4y00bXeIMTB6fnnks2ddj6JMBHkY0KKeDiXH4Jyn42lRLPouq2mPAfp2xsTUfVNmvcnOQbc2tRmP9MGO7FM41f1vZFndiV/Ek4uFojdfPJIpHgM1aSWsraJLCmZmDN7r6jEuUxesKJTmWt/6zqKYK5ZmlP835U7bTiE3JDL1vHfdZ/WO1GUKig=
  - secure: BT2qNxTuLhjVXa42En2RzO5xnQ71n4hYX7rnyGhyn6Bz2SYjuFukSY72Q2vqOULziEK8q/ku0+mIFXdP6IPK6mRntx8qpqtD7qRCfJIZgJ2UGZbnVEQOzzpy6+R+gOPic0mwPZx72gESX8uW5Zsj5ro9j3RokFn+vhfw/h+UZJm7z+KiGGWBh5Td07pb2qpL3/H1DleFcFAlvXdLbZcjhNk7Mn3yuJvmktxJUD5ISknCOirEO8t3OT5pLXkq01Z4VazGstvUSn8r9N5qBpn8gSJDpt3I38e5z++PvxnSdLxbBDE3Y2UKEF48QVIO/h3DOx9Hw/bVqdA8TyuA/z2gdS9JEWTjr4QP7ti6bFe8zjCsSgrlSGn+sgriTx5Yny9su++P7+1u6n5JPV9CpDNSC4ZU7plOjTPApSy+TMkVHSqRk0MB8f1Y3oJRKtxDgglx3dJv4plZNd5/EnxwZk2a5+8SB2N0rfaHR2fupqWykr9J2U654pxirc0IPrCc966GhKnPBL7rpoqPO+O5t4W1s+WatIihGDhuYJf9wEhSIBwRdEf5cDOqotMlqYL5H8vhGPBCK3JUmgW/wVJXlRf6Mp+DdwmDDCscJsYAtFDFZU6tuAYyzxXef7XOsuRQ42q+2Rk5yDt5XUt6J3oMmqb6vBude2BpocbGcqP3twNkOCk=
  - secure: "Em0gPbHUk/RDOXaC/Y4ddtePVv21cHltj6z5noIS3Ne3Z4OgDzxTknce4QWDjkjfeIToFPuCZiesiifWgw1eAx9xKDA4ijDe7PmMICU2nnn17YRk6bRUBFtX4bb6c0BN7PrbaQOMTbgqt19TntPyELHQ3L0btvo51wV0siF/K6uvS3oK45XRYLqThYCjvoygehGRjd6WaNqvGForKZvj652sPjwmJFhpHYpCxyoZ4LaXcLTRQBQ4M4h1UwIbd0V9Hn0AiOR8+KIqMzwrbIFrtt2vN5RoUfoZkRK2OumcsvydVbliGndr5fz+hm08tTEuwpW6dUffogvsp72Dk6rIKoDckEBwZ6M10u4ECj+Op3byVyR5/a84BQQ/RzaDFB69J1wVZnWLuMxDT5WQTLzoTJzYsDm03/c8X+ojeWsGwn9XqxKIyoHhltra1lLmRSa3TavAQWj9Lol4qvqz4l/ftMo0wTrD75JwyRzK/llwO+U5XIStXIsaXtmxxfbRSdJt8pl24s8DWQQ9ugT6RLy6/1OsFrTwToybO4oeGYhmbwwo7bwheG92bA8uC1SDm6ICnh3VbVnzbgAaxtZ/gNk6yGtNKSN50flj45nhvT0BQyzg67PwZMYlLyeLUVuMSFDWjHI+mTeV5qRvn6pq2poZ0DFzJhZE1EJDWBvmS8o6ZH0="

before_install:
 - >
  if [ "x${ENCRYPTION_PASSWORD}" != "x" ]; then
    openssl aes-256-cbc -pass pass:${ENCRYPTION_PASSWORD} -in secring.gpg.enc -out local.secring.gpg -d
    openssl aes-256-cbc -pass pass:${ENCRYPTION_PASSWORD} -in pubring.gpg.enc -out local.pubring.gpg -d
    openssl aes-256-cbc -pass pass:${ENCRYPTION_PASSWORD} -in credentials.sbt.enc -out local.credentials.sbt -d
  fi

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts jvmopts clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage

# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=

after_success:
 - >
  test "${TRAVIS_PULL_REQUEST}" = 'false' &&
  test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' &&
  sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' clean publishSigned

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6120fddea5fd58b6bc51
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
